package com.saul.panelium.admin;

import com.saul.panelium.catalog.*; import com.saul.panelium.media.ObjectStorage; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import org.springframework.web.server.ResponseStatusException; import java.math.BigDecimal; import java.util.*;

@RestController @RequestMapping("/api/admin")
public class AdminController{
 private final WorkRepository works; private final ChapterRepository chapters; private final ChapterPageRepository pages; private final ObjectStorage storage;
 AdminController(WorkRepository works,ChapterRepository chapters,ChapterPageRepository pages,ObjectStorage storage){this.works=works;this.chapters=chapters;this.pages=pages;this.storage=storage;}
 @PostMapping("/works") @ResponseStatus(HttpStatus.CREATED) CatalogController.WorkCard createWork(@Valid @RequestBody WorkRequest b){String slug=b.slug().toLowerCase().replaceAll("[^a-z0-9]+","-").replaceAll("(^-|-$)","");if(works.findBySlug(slug).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"El slug ya existe");return CatalogController.WorkCard.from(works.save(new Work(slug,b.title(),b.author(),b.synopsis(),b.format().toUpperCase(),b.status(),"uploaded-placeholder",b.accent())));}
 @PostMapping(value="/works/{id}/cover",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) Map<String,String> cover(@PathVariable Long id,@RequestPart MultipartFile file)throws Exception{validateImage(file);var work=works.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));String key="covers/"+id+"/"+UUID.randomUUID()+extension(file);storage.put(key,file);work.setCoverKey("/api/assets/"+key);works.save(work);return Map.of("url","/api/assets/"+key);}
 @PostMapping("/works/{id}/chapters") @ResponseStatus(HttpStatus.CREATED) ChapterResponse chapter(@PathVariable Long id,@Valid @RequestBody ChapterRequest b){var work=works.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));var c=chapters.save(new Chapter(work,b.number(),b.title(),Math.max(1,b.pageCount()),b.direction().toUpperCase()));return new ChapterResponse(c.getId(),c.getTitle());}
 @PostMapping(value="/chapters/{id}/pages",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @Transactional List<String> uploadPages(@PathVariable Long id,@RequestPart("files") List<MultipartFile> files)throws Exception{var chapter=chapters.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));if(files.isEmpty())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Selecciona al menos una página");pages.deleteByChapterId(id);List<String> urls=new ArrayList<>();int number=1;for(var file:files){validateImage(file);String key="chapters/"+id+"/"+String.format("%04d",number)+"-"+UUID.randomUUID()+extension(file);storage.put(key,file);pages.save(new ChapterPage(chapter,number++,key,file.getContentType()));urls.add("/api/assets/"+key);}chapter.setPageCount(files.size());chapters.save(chapter);return urls;}
 private void validateImage(MultipartFile f){if(f.isEmpty()||f.getContentType()==null||!f.getContentType().startsWith("image/"))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Solo se aceptan imágenes");if(f.getSize()>15_000_000)throw new ResponseStatusException(HttpStatus.PAYLOAD_TOO_LARGE,"Cada imagen debe pesar menos de 15 MB");}
 private String extension(MultipartFile f){String n=Optional.ofNullable(f.getOriginalFilename()).orElse("");int dot=n.lastIndexOf('.');return dot>=0?n.substring(dot).toLowerCase():".img";}
 public record WorkRequest(@NotBlank String slug,@NotBlank String title,@NotBlank String author,@NotBlank String synopsis,@Pattern(regexp="MANGA|COMIC|WEBTOON",flags=Pattern.Flag.CASE_INSENSITIVE)String format,@NotBlank String status,@Pattern(regexp="#[0-9a-fA-F]{6}")String accent){}
 public record ChapterRequest(@NotNull @DecimalMin("0.01")BigDecimal number,@NotBlank String title,@Min(1)int pageCount,@Pattern(regexp="RTL|LTR|VERTICAL",flags=Pattern.Flag.CASE_INSENSITIVE)String direction){}
 public record ChapterResponse(Long id,String title){}
}
