create table work (
 id bigint generated by default as identity primary key,
 slug varchar(100) not null unique,
 title varchar(180) not null,
 author varchar(140) not null,
 synopsis text not null,
 format varchar(20) not null,
 status varchar(30) not null,
 cover_key varchar(200) not null,
 accent varchar(20) not null
);
create table chapter (
 id bigint generated by default as identity primary key,
 work_id bigint not null references work(id) on delete cascade,
 number numeric(8,2) not null,
 title varchar(180) not null,
 page_count int not null check(page_count > 0),
 direction varchar(20) not null,
 unique(work_id,number)
);
create table reading_progress (
 id bigint generated by default as identity primary key,
 reader_id varchar(80) not null,
 work_id bigint not null references work(id) on delete cascade,
 chapter_id bigint not null references chapter(id) on delete cascade,
 page_number int not null check(page_number > 0),
 updated_at timestamp with time zone not null default current_timestamp,
 unique(reader_id,work_id)
);
insert into work(slug,title,author,synopsis,format,status,cover_key,accent) values
('neon-ronin','Neon Ronin','Mara Kuro','En una ciudad donde los recuerdos se compran, Akari persigue el fragmento que puede devolverle su identidad.','MANGA','En publicación','neon-ronin','#ff4d8d'),
('orbita-cero','Órbita Cero','Lina Vega','Una tripulación de rescate descubre una señal imposible en una estación abandonada.','COMIC','Completa','orbita-cero','#5be7c4'),
('jardin-de-tinta','El jardín de tinta','Noa Serrano','Cada planta conserva una historia; abrir la flor equivocada puede reescribir el presente.','WEBTOON','En publicación','jardin-de-tinta','#b69cff');
insert into chapter(work_id,number,title,page_count,direction) values
((select id from work where slug='neon-ronin'),1,'Lluvia de neón',6,'RTL'),
((select id from work where slug='neon-ronin'),2,'Memoria fantasma',6,'RTL'),
((select id from work where slug='orbita-cero'),1,'Señal de auxilio',6,'LTR'),
((select id from work where slug='jardin-de-tinta'),1,'La primera semilla',6,'VERTICAL');
