create table app_user (
 id bigint generated by default as identity primary key,
 name varchar(120) not null,
 email varchar(180) not null unique,
 password_hash varchar(120) not null,
 user_role varchar(20) not null,
 created_at timestamp with time zone not null default current_timestamp
);

create table chapter_page (
 id bigint generated by default as identity primary key,
 chapter_id bigint not null references chapter(id) on delete cascade,
 page_number int not null check(page_number > 0),
 object_key varchar(300) not null,
 content_type varchar(100) not null,
 unique(chapter_id, page_number)
);
